unit NtUiBackend.Sids.Hierarchy;

{
  This unit provides the logic for listing the hierarchy of SIDs.
}

interface

uses
  NtUtils, DevirtualizedTree, NtUiBackend.Sids, NtUiCommon.Interfaces;

type
  TSidHierarchyPlaceholder = (
    spNone,
    spLogons,
    spDomainAccounts,
    spGroupCapabilities,
    spServices,
    spTasks,
    spVirtualAccounts,
    spAppContainers,
    spAppCapabilities,
    spAppSiloCapabilities,
    spPackages
  );

  ISidHierarchyNode = interface (ISidNode)
    ['{3D739765-6462-4B9D-A696-33F42E57FEED}']
    function GetDefinition: String;
    function GetPlaceholder: TSidHierarchyPlaceholder;
    property Definition: String read GetDefinition;
    property Placeholder: TSidHierarchyPlaceholder read GetPlaceholder;
  end;

// Add SID hierarchy nodes to a tree control
procedure NtUiLibAddSidHierarchyNodes(
  Tree: TTreeNodeInterfaceProvider
);

implementation

uses
  Ntapi.WinNt, Ntapi.ntpebteb, NtUtils.Security.Sid, NtUtils.Lsa.Sid,
  DelphiUiLib.Reflection, DelphiUiLib.Reflection.Strings, VirtualTrees,
  DevirtualizedTree.Provider, NtUiCommon.Helpers, System.UITypes,
  NtUiCommon.Colors;

type
  TSidHierarchySpecialHandling = (
    shNone,
    shNtPseudoDomain,
    shPerSessionSid
  );

  TSidHierarchyNodeDefinition = record
    Authorities: TArray<Cardinal>;
    Definition: String;
    Placeholder: TSidHierarchyPlaceholder;
    SpecialHandling: TSidHierarchySpecialHandling;
  end;

const
  HIERARCHY_DEFINITIONS: array [0..172] of TSidHierarchyNodeDefinition = (
    (Authorities: [SECURITY_NULL_SID_AUTHORITY]; Definition: '{SECURITY_NULL_SID_AUTHORITY}'),
    (Authorities: [SECURITY_NULL_SID_AUTHORITY, SECURITY_NULL_RID]; Definition: '{SECURITY_NULL_SID_AUTHORITY, SECURITY_NULL_RID}'),
    (Authorities: [SECURITY_WORLD_SID_AUTHORITY]; Definition: '{SECURITY_WORLD_SID_AUTHORITY}'),
    (Authorities: [SECURITY_WORLD_SID_AUTHORITY, SECURITY_WORLD_RID]; Definition: '{SECURITY_WORLD_SID_AUTHORITY, SECURITY_WORLD_RID}'),
    (Authorities: [SECURITY_LOCAL_SID_AUTHORITY]; Definition: '{SECURITY_LOCAL_SID_AUTHORITY}'),
    (Authorities: [SECURITY_LOCAL_SID_AUTHORITY, SECURITY_LOCAL_RID]; Definition: '{SECURITY_LOCAL_SID_AUTHORITY, SECURITY_LOCAL_RID}'),
    (Authorities: [SECURITY_LOCAL_SID_AUTHORITY, SECURITY_LOCAL_LOGON_RID]; Definition: '{SECURITY_LOCAL_SID_AUTHORITY, SECURITY_LOCAL_LOGON_RID}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_RID]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_RID}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_GROUP_RID]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_GROUP_RID}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_SERVER_RID]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_SERVER_RID}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_GROUP_SERVER_RID]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_GROUP_SERVER_RID}'),
    (Authorities: [SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_RIGHTS_RID]; Definition: '{SECURITY_CREATOR_SID_AUTHORITY, SECURITY_CREATOR_OWNER_RIGHTS_RID}'),
    (Authorities: [SECURITY_NON_UNIQUE_AUTHORITY]; Definition: '{SECURITY_NON_UNIQUE_AUTHORITY}'),
    (Authorities: [SECURITY_NT_AUTHORITY]; Definition: '{SECURITY_NT_AUTHORITY}'; SpecialHandling: shNtPseudoDomain),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_DIALUP_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_DIALUP_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NETWORK_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NETWORK_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BATCH_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BATCH_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_INTERACTIVE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_INTERACTIVE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOGON_IDS_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOGON_IDS_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOGON_IDS_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOGON_IDS_RID, *, *}'; Placeholder: spLogons),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_SERVICE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_SERVICE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_ANONYMOUS_LOGON_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_ANONYMOUS_LOGON_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PROXY_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PROXY_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_ENTERPRISE_CONTROLLERS_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_ENTERPRISE_CONTROLLERS_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PRINCIPAL_SELF_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PRINCIPAL_SELF_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_AUTHENTICATED_USER_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_AUTHENTICATED_USER_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_RESTRICTED_CODE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_RESTRICTED_CODE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_TERMINAL_SERVER_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_TERMINAL_SERVER_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_REMOTE_LOGON_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_REMOTE_LOGON_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_THIS_ORGANIZATION_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_THIS_ORGANIZATION_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_IUSER_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_IUSER_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOCAL_SYSTEM_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOCAL_SYSTEM_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOCAL_SERVICE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOCAL_SERVICE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NETWORK_SERVICE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NETWORK_SERVICE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_IS_COMPOUNDED]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_IS_COMPOUNDED}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_CONTAINS_CLAIMS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_CONTAINS_CLAIMS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NT_NON_UNIQUE, *, *, *}'; Placeholder: spDomainAccounts),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_ENTERPRISE_READONLY_CONTROLLERS_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_ENTERPRISE_READONLY_CONTROLLERS_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_GUESTS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_GUESTS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_POWER_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_POWER_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ACCOUNT_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ACCOUNT_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_SYSTEM_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_SYSTEM_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PRINT_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PRINT_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_BACKUP_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_BACKUP_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REPLICATOR]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REPLICATOR}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RAS_SERVERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RAS_SERVERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PREW2KCOMPACCESS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PREW2KCOMPACCESS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REMOTE_DESKTOP_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REMOTE_DESKTOP_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_NETWORK_CONFIGURATION_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_NETWORK_CONFIGURATION_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_INCOMING_FOREST_TRUST_BUILDERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_INCOMING_FOREST_TRUST_BUILDERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_MONITORING_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_MONITORING_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_LOGGING_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_LOGGING_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_AUTHORIZATIONACCESS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_AUTHORIZATIONACCESS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_TS_LICENSE_SERVERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_TS_LICENSE_SERVERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DCOM_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DCOM_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_IUSERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_IUSERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CRYPTO_OPERATORS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CRYPTO_OPERATORS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CACHEABLE_PRINCIPALS_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CACHEABLE_PRINCIPALS_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_NON_CACHEABLE_PRINCIPALS_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_NON_CACHEABLE_PRINCIPALS_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_EVENT_LOG_READERS_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_EVENT_LOG_READERS_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CERTSVC_DCOM_ACCESS_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CERTSVC_DCOM_ACCESS_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_REMOTE_ACCESS_SERVERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_REMOTE_ACCESS_SERVERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_ENDPOINT_SERVERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_ENDPOINT_SERVERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_MANAGEMENT_SERVERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_RDS_MANAGEMENT_SERVERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_HYPER_V_ADMINS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_HYPER_V_ADMINS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ACCESS_CONTROL_ASSISTANCE_OPS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ACCESS_CONTROL_ASSISTANCE_OPS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REMOTE_MANAGEMENT_USERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REMOTE_MANAGEMENT_USERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DEFAULT_ACCOUNT]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DEFAULT_ACCOUNT}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_STORAGE_REPLICA_ADMINS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_STORAGE_REPLICA_ADMINS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DEVICE_OWNERS]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DEVICE_OWNERS}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_BUILTIN_DOMAIN_RID, *, *, *, *, *, *, *, *}'; Placeholder: spGroupCapabilities),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WRITE_RESTRICTED_CODE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WRITE_RESTRICTED_CODE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_NTLM_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_NTLM_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_SCHANNEL_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_SCHANNEL_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_DIGEST_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_DIGEST_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_CRED_TYPE_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_CRED_TYPE_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_CRED_TYPE_BASE_RID, SECURITY_CRED_TYPE_THIS_ORG_CERT_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_CRED_TYPE_BASE_RID, SECURITY_CRED_TYPE_THIS_ORG_CERT_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID, SECURITY_SERVICE_ID_GROUP_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID, SECURITY_SERVICE_ID_GROUP_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_SERVICE_ID_BASE_RID, *, *, *, *, *}'; Placeholder: spServices),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_APPPOOL_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_APPPOOL_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_VIRTUALSERVER_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_VIRTUALSERVER_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_VIRTUALSERVER_ID_BASE_RID, SECURITY_VIRTUALSERVER_ID_GROUP_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_VIRTUALSERVER_ID_BASE_RID, SECURITY_VIRTUALSERVER_ID_GROUP_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_USERMODEDRIVERHOST_ID_BASE_RID, 0, 0, 0, 0, SECURITY_USERMODEDRIVERHOST_ID_GROUP_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_USERMODEDRIVERHOST_ID_BASE_RID, 0, 0, 0, 0, SECURITY_USERMODEDRIVERHOST_ID_GROUP_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_CLOUD_INFRASTRUCTURE_SERVICES_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_CLOUD_INFRASTRUCTURE_SERVICES_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WMIHOST_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WMIHOST_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_TASK_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_TASK_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_TASK_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_TASK_ID_BASE_RID, *, *, *, *, *}'; Placeholder: spTasks),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_NFS_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_NFS_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_COM_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_COM_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP, 0]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP, 0}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP, 1]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINDOW_MANAGER_BASE_RID, SECURITY_WINDOW_MANAGER_GROUP, %SessionId%}'; SpecialHandling: shPerSessionSid),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_RDV_GFX_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_RDV_GFX_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_DASHOST_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_DASHOST_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_USERMANAGER_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_USERMANAGER_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINRM_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINRM_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_CCG_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_CCG_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP, 0]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP, 0}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP, 1]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_UMFD_BASE_RID, SECURITY_UMFD_GROUP, %SessionId%}'; SpecialHandling: shPerSessionSid),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_MAX_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_MIN_BASE_RID..SECURITY_MAX_BASE_RID}'; Placeholder: spVirtualAccounts),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_WINDOWSMOBILE_ID_BASE_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_WINDOWSMOBILE_ID_BASE_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOCAL_ACCOUNT_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOCAL_ACCOUNT_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_LOCAL_ACCOUNT_AND_ADMIN_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_LOCAL_ACCOUNT_AND_ADMIN_RID}'),
    (Authorities: [SECURITY_NT_AUTHORITY, SECURITY_OTHER_ORGANIZATION_RID]; Definition: '{SECURITY_NT_AUTHORITY, SECURITY_OTHER_ORGANIZATION_RID}'),
    (Authorities: [SECURITY_SITESERVER_AUTHORITY]; Definition: '{SECURITY_SITESERVER_AUTHORITY}'),
    (Authorities: [SECURITY_INTERNETSITE_AUTHORITY]; Definition: '{SECURITY_INTERNETSITE_AUTHORITY}'),
    (Authorities: [SECURITY_EXCHANGE_AUTHORITY]; Definition: '{SECURITY_EXCHANGE_AUTHORITY}'),
    (Authorities: [SECURITY_RESOURCE_MANAGER_AUTHORITY]; Definition: '{SECURITY_RESOURCE_MANAGER_AUTHORITY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID, SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID, SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID, SECURITY_BUILTIN_PACKAGE_ANY_RESTRICTED_PACKAGE]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID, SECURITY_BUILTIN_PACKAGE_ANY_RESTRICTED_PACKAGE}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_APP_PACKAGE_BASE_RID, *, *, *, *, *, *, *}'; Placeholder: spAppContainers),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_INTERNET_CLIENT]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_INTERNET_CLIENT}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_PICTURES_LIBRARY]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_PICTURES_LIBRARY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_VIDEOS_LIBRARY]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_VIDEOS_LIBRARY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_MUSIC_LIBRARY]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_MUSIC_LIBRARY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_DOCUMENTS_LIBRARY]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_DOCUMENTS_LIBRARY}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_REMOVABLE_STORAGE]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_REMOVABLE_STORAGE}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APPOINTMENTS]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APPOINTMENTS}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_CONTACTS]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_CONTACTS}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_RID}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_RID, *, *, *, *, *, *, *, *}'; Placeholder: spAppCapabilities),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_SILO_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_SILO_RID}'),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_SILO_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, SECURITY_CAPABILITY_APP_SILO_RID, *, *, *, *, *, *, *, *}'; Placeholder: spAppSiloCapabilities),
    (Authorities: [SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID]; Definition: '{SECURITY_APP_PACKAGE_AUTHORITY, SECURITY_CAPABILITY_BASE_RID, *, *, *, *, *, *, *}'; Placeholder: spPackages),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_UNTRUSTED_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_UNTRUSTED_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_LOW_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_LOW_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_MEDIUM_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_MEDIUM_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_MEDIUM_PLUS_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_MEDIUM_PLUS_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_HIGH_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_HIGH_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_SYSTEM_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_SYSTEM_RID}'),
    (Authorities: [SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_PROTECTED_PROCESS_RID]; Definition: '{SECURITY_MANDATORY_LABEL_AUTHORITY, SECURITY_MANDATORY_PROTECTED_PROCESS_RID}'),
    (Authorities: [SECURITY_SCOPED_POLICY_ID_AUTHORITY]; Definition: '{SECURITY_SCOPED_POLICY_ID_AUTHORITY}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_AUTHORITY_ASSERTED_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_AUTHORITY_ASSERTED_RID}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_SERVICE_ASSERTED_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_SERVICE_ASSERTED_RID}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_FRESH_KEY_AUTH_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_FRESH_KEY_AUTH_RID}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_TRUST_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_TRUST_RID}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_PROPERTY_MFA_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_PROPERTY_MFA_RID}'),
    (Authorities: [SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_PROPERTY_ATTESTATION_RID]; Definition: '{SECURITY_AUTHENTICATION_AUTHORITY, SECURITY_AUTHENTICATION_KEY_PROPERTY_ATTESTATION_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_NONE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_NONE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_NONE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_NONE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_NONE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_NONE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_AUTHENTICODE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_AUTHENTICODE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_ANTIMALWARE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_ANTIMALWARE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_APP_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_APP_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINDOWS_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINDOWS_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINTCB_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_LITE_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINTCB_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_AUTHENTICODE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_AUTHENTICODE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_ANTIMALWARE_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_ANTIMALWARE_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_APP_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_APP_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINDOWS_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINDOWS_RID}'),
    (Authorities: [SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINTCB_RID]; Definition: '{SECURITY_PROCESS_TRUST_AUTHORITY, SECURITY_PROCESS_PROTECTION_TYPE_FULL_RID, SECURITY_PROCESS_PROTECTION_LEVEL_WINTCB_RID}')
  );

  PLACEHOLDER_SDDL: array [TSidHierarchyPlaceholder] of String = (
    '',
    'S-1-5-5-[+2 values]',
    'S-1-5-21-[+3 values]',
    'S-1-5-32-[+8 values]',
    'S-1-5-80-[+5 values]',
    'S-1-5-87-[+5 values]',
    'S-1-5-[80..111]',
    'S-1-15-2-[+7 or +11 values]',
    'S-1-15-3-1024-[+8 values]',
    'S-1-15-3-65536-[+8 values]',
    'S-1-15-3-[+7 values]'
  );

  PLACEHOLDER_TEXT: array [TSidHierarchyPlaceholder] of String = (
    '',
    'Logon SIDs...',
    'Domain Accounts...',
    'Group Capabilities...',
    'Service SIDs...',
    'Task SIDs...',
    'Virtual Account SIDs...',
    'AppContainer SIDs...',
    'App Capability SIDs...',
    'AppSilo Capability SIDs...',
    'Package SIDs...'
  );

const
  colSid = 0;
  colFriendlyName = 1;
  colSidType = 2;
  colDefinition = 3;
  colMax = 4;

type
  TSidHierarchyNode = class (TNodeProvider, ISidHierarchyNode,
    IOptionalModalResultNode)
  protected
    FDefinition: String;
    FSidName: TTranslatedName;
    FPlaceholder: TSidHierarchyPlaceholder;
  public
    function GetDefinition: String;
    function GetSidName: TTranslatedName;
    function GetPlaceholder: TSidHierarchyPlaceholder;
    function GetAllowsModalReturn: Boolean;
    procedure Initialize; override;
    constructor Create(
      const SidName: TTranslatedName;
      const Definition: String;
      Placeholder: TSidHierarchyPlaceholder = spNone
    );
  end;

{ TSidHierarchyNode }

constructor TSidHierarchyNode.Create;
begin
  inherited Create(colMax);
  FDefinition := Definition;
  FSidName := SidName;
  FPlaceholder := Placeholder;
end;

function TSidHierarchyNode.GetAllowsModalReturn;
begin
  // Only real SID nodes count as modal returns
  Result := (FPlaceholder = spNone);
end;

function TSidHierarchyNode.GetDefinition;
begin
  Result := FDefinition;
end;

function TSidHierarchyNode.GetPlaceholder;
begin
  Result := FPlaceholder;
end;

function TSidHierarchyNode.GetSidName;
begin
  Result := FSidName;
end;

procedure TSidHierarchyNode.Initialize;
begin
  inherited;
  FColumnText[colDefinition] := FDefinition;

  if FPlaceholder = spNone then
  begin
    FColumnText[colSid] := RtlxSidToString(FSidName.Sid);

    if FSidName.IsValid then
    begin
      FColumnText[colFriendlyName] := FSidName.FullName;
      FColumnText[colSidType] := TType.Represent(FSidName.SidType).Text;
    end;

    FHint := BuildHint([
      THintSection.New('SID', FColumnText[colSid]),
      THintSection.New('Friendly Name', FColumnText[colFriendlyName]),
      THintSection.New('SID Type', FColumnText[colSidType]),
      THintSection.New('Definition', FColumnText[colDefinition])
    ]);
  end
  else
  begin
    // Prepare the link text
    FColumnText[colSid] := PLACEHOLDER_SDDL[FPlaceholder];
    FColumnText[colFriendlyName] := PLACEHOLDER_TEXT[FPlaceholder];

    // Adjust styles
    SetFontColor(ColorSettings.clForegroundInactive);
    SetFontColorForColumn(colFriendlyName, ColorSettings.clForegroundLink);
    SetFontStyleForColumn(colFriendlyName, [TFontStyle.fsUnderline]);
    SetCursor(crHandPoint);
  end;
end;

function NtUiLibpAdjustSessionRid(
  const Sid: ISid
): ISid;
var
  SessionId: TSessionId;
begin
  SessionId := RtlGetCurrentPeb.SessionID;

  // The placeholder has sessions 0 and 1 by default. Replace 1 with the current
  // session if different.
  if (SessionId <= 1) or not RtlxMakeSiblingSid(Result, Sid,
    SessionId).IsSuccess then
    Result := Sid;
end;

function NtUiLibMakeSidHierarchyNodes(
): TArray<ISidHierarchyNode>;
var
  i, Count: Integer;
  Sid: ISid;
  SIDs: TArray<ISid>;
  Names: TArray<TTranslatedName>;
  PlaceholderName: TTranslatedName;
  LookupSucceeded: Boolean;
begin
  // Determine the number of SIDs requiring translation
  Count := 0;

  for i := 0 to High(HIERARCHY_DEFINITIONS) do
    if (HIERARCHY_DEFINITIONS[i].Placeholder = spNone) and
      (HIERARCHY_DEFINITIONS[i].SpecialHandling in [shNone, shPerSessionSid]) then
      Inc(Count);

  // Save them
  SetLength(SIDs, Count);
  Count := 0;

  for i := 0 to High(HIERARCHY_DEFINITIONS) do
    if (HIERARCHY_DEFINITIONS[i].Placeholder = spNone) and
      (HIERARCHY_DEFINITIONS[i].SpecialHandling in [shNone, shPerSessionSid]) then
    begin
      Sid := RtlxMakeSidFromArray(HIERARCHY_DEFINITIONS[i].Authorities);

      // Alter per-session SIDs to reflect the current session ID
      if HIERARCHY_DEFINITIONS[i].SpecialHandling = shPerSessionSid then
        Sid := NtUiLibpAdjustSessionRid(Sid);

      SIDs[Count] := Sid;
      Inc(Count);
    end;

  // Lookup SIDs in bulk
  LookupSucceeded := LsaxLookupSids(SIDs, Names).IsSuccess;

  // Create node providers
  SetLength(Result, Length(HIERARCHY_DEFINITIONS));
  PlaceholderName := Default(TTranslatedName);
  Count := 0;

  for i := 0 to High(Result) do
    if (HIERARCHY_DEFINITIONS[i].Placeholder = spNone) and
      (HIERARCHY_DEFINITIONS[i].SpecialHandling in [shNone, shPerSessionSid]) then
    begin
      // Create a node for a normal SID
      Result[i] := TSidHierarchyNode.Create(
        Names[Count],
        HIERARCHY_DEFINITIONS[i].Definition,
        spNone
      );

      Inc(Count);
    end
    else
    begin
      PlaceholderName.SID := RtlxMakeSidFromArray(
        HIERARCHY_DEFINITIONS[i].Authorities);

      if (HIERARCHY_DEFINITIONS[i].SpecialHandling = shNtPseudoDomain) and
        LookupSucceeded then
      begin
        // Fake a lookup for 'NT Pseudo Domain' since mixing it with other SIDs
        // in a bulk translation has a side-effect on NT AUTHORITY domain name.
        PlaceholderName.DomainName := 'NT Pseudo Domain';
        PlaceholderName.SidType := SidTypeDomain;
      end
      else
      begin
        PlaceholderName.DomainName := '';
        PlaceholderName.SidType := SidTypeUndefined;
      end;

      // Create a node for the placeholder
      Result[i] := TSidHierarchyNode.Create(
        PlaceholderName,
        HIERARCHY_DEFINITIONS[i].Definition,
        HIERARCHY_DEFINITIONS[i].Placeholder
      );
    end;
end;

procedure NtUiLibAddSidHierarchyNodes;
var
  Nodes: TArray<ISidHierarchyNode>;
  Parents: TArray<ISidHierarchyNode>;
  i, j: Integer;
begin
  // Collect sorted nodes
  Nodes := NtUiLibMakeSidHierarchyNodes;

  Parents := nil;
  SetLength(Parents, Length(Nodes));

  // For each node, look backwards for its parent
  for i := 0 to High(Nodes) do
    for j := i - 1 downto 0 do
      if RtlxIsChildSid(Nodes[i].SidName.Sid, Nodes[j].SidName.Sid, True) then
      begin
        Parents[i] := Nodes[j];
        Break;
      end;

  // Attache them to the tree
  Tree.BeginUpdateAuto;
  Tree.ClearItems;

  // Note: since nodes are pre-ordered, if the parent exists, it has already
  // been attached
  for i := 0 to High(Nodes) do
    Tree.AddItem(Nodes[i], Parents[i]);
end;

end.
